const Map productImagePath = {
  'Alpha Man': 'assets/images/Alphaman_small.png',
  'Bioprost': 'assets/images/Bioprost_bottle_big.png',
  'Cardiox': 'assets/images/Cardiox_bottle_big.png',
  'Flexacil': 'assets/images/Flexacil_es2.png',
  'Glyconorm': 'assets/images/Glyconorm_bottle_small.png',
  'Gialuron Revita': 'assets/images/Placeholder.png',
  'Green Coffee' : 'assets/images/Placeholder.png',
  'Slim Latte' : 'assets/images/Placeholder.png',
  'SlimFit' : 'assets/images/Placeholder.png',
  'Turboslim': 'assets/images/Turboslim_20.png',
  'Tiburex': 'assets/images/Placeholder.png',
  'Test product': 'assets/images/Placeholder.png',
  'TestoStirol': 'assets/images/Placeholder.png',
};
